namespace ICMarketsTest.Core.BlockchainSnapshots.GetBlockchainSnapshots;

public interface IGetBlockchainSnapshotsQueryExecutor : IQueryExecutor<GetBlockchainSnapshotsQuery, PagedResult<BlockchainSnapshot>>;